; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
include_dir=uCNC
src_dir=uCNC
default_envs = ESP32-MKS-TINYBEE
extra_configs = 
  uCNC/src/hal/boards/avr/avr.ini
  uCNC/src/hal/boards/samd21/samd21.ini
  uCNC/src/hal/boards/stm32/stm32.ini
  uCNC/src/hal/boards/esp8266/esp8266.ini
  uCNC/src/hal/boards/lpc176x/lpc176x.ini
  uCNC/src/hal/boards/esp32/esp32.ini
  uCNC/src/hal/boards/rp2040/rp2040.ini
	uCNC/src/hal/boards/rp2350/rp2350.ini
  uCNC/src/hal/mcus/virtual/virtual.ini

[env]
framework = arduino
monitor_speed = 115200
monitor_eol = LF
monitor_echo = yes
monitor_filters = colorize, time
extra_scripts =
	pre:ucnc_modules.py
;µCNC web builder generated config
custom_ucnc_modules_url = https://github.com/staskaaa-netizen/uCNC-modules/archive/refs/heads/pre-alpha.zip
custom_ucnc_modules = ui_snapshot, cam_keyboard, leanCam, ra8876_display, sd_card_v2, g7_g8, g33
board =
