// Standalone LeanCam HDMI configuration, copied from the working
// Waveshare800x600 DispHSTX project.
#ifndef LEANCAM_HSTX_CONFIG_H
#define LEANCAM_HSTX_CONFIG_H

#define DISPHSTX_PICOSDK 1
#define USE_TEXT 1
#define USE_RAND 0

#ifndef PICO_PIO_USE_GPIO_BASE
#define PICO_PIO_USE_GPIO_BASE 1
#endif

#define USE_DISPHSTX 1
#define USE_DRAWCAN 1
#define USE_DRAWCAN6 1

#define DISPHSTX_USE_DVI 1
#define DISPHSTX_USE_VGA 0
#define DISPHSTX_DISP_SEL -1
#define DISPHSTX_WIDTHMAX 800
#define DISPHSTX_STRIP_MAX 1
#define DISPHSTX_SLOT_MAX 1

#ifndef LEANCAM_USE_HSTX_PLL
#define LEANCAM_USE_HSTX_PLL 0
#endif

#define DISPHSTX_USEPLL LEANCAM_USE_HSTX_PLL

#define DISPHSTX_DVI_D2P 12
#define DISPHSTX_DVI_D2M 13
#define DISPHSTX_DVI_D1P 16
#define DISPHSTX_DVI_D1M 17
#define DISPHSTX_DVI_D0P 18
#define DISPHSTX_DVI_D0M 19
#define DISPHSTX_DVI_CLKP 14
#define DISPHSTX_DVI_CLKM 15

#define DISPHSTX_USE_FORMAT_1 0
#define DISPHSTX_USE_FORMAT_2 0
#define DISPHSTX_USE_FORMAT_3 0
#define DISPHSTX_USE_FORMAT_4 0
#define DISPHSTX_USE_FORMAT_6 0
#define DISPHSTX_USE_FORMAT_8 0
#define DISPHSTX_USE_FORMAT_12 0
#define DISPHSTX_USE_FORMAT_15 0
#define DISPHSTX_USE_FORMAT_16 0
#define DISPHSTX_USE_FORMAT_1_PAL 0
#define DISPHSTX_USE_FORMAT_2_PAL 0
#define DISPHSTX_USE_FORMAT_3_PAL 0
#define DISPHSTX_USE_FORMAT_4_PAL 0
#define DISPHSTX_USE_FORMAT_6_PAL 1
#define DISPHSTX_USE_FORMAT_8_PAL 0
#define DISPHSTX_USE_FORMAT_COL 0
#define DISPHSTX_USE_FORMAT_MTEXT 0
#define DISPHSTX_USE_FORMAT_ATEXT 0
#define DISPHSTX_USE_FORMAT_TILE4_8 0
#define DISPHSTX_USE_FORMAT_TILE8_8 0
#define DISPHSTX_USE_FORMAT_TILE16_8 0
#define DISPHSTX_USE_FORMAT_TILE32_8 0
#define DISPHSTX_USE_FORMAT_TILE4_8_PAL 0
#define DISPHSTX_USE_FORMAT_TILE8_8_PAL 0
#define DISPHSTX_USE_FORMAT_TILE16_8_PAL 0
#define DISPHSTX_USE_FORMAT_TILE32_8_PAL 0
#define DISPHSTX_USE_FORMAT_HSTX_15 0
#define DISPHSTX_USE_FORMAT_HSTX_16 0
#define DISPHSTX_USE_FORMAT_PAT_8 0
#define DISPHSTX_USE_FORMAT_PAT_8_PAL 0
#define DISPHSTX_USE_FORMAT_RLE8 0
#define DISPHSTX_USE_FORMAT_RLE8_PAL 0
#define DISPHSTX_USE_FORMAT_ATTR1_PAL 0
#define DISPHSTX_USE_FORMAT_ATTR2_PAL 0
#define DISPHSTX_USE_FORMAT_ATTR3_PAL 0
#define DISPHSTX_USE_FORMAT_ATTR4_PAL 0
#define DISPHSTX_USE_FORMAT_ATTR5_PAL 0
#define DISPHSTX_USE_FORMAT_ATTR6_PAL 0
#define DISPHSTX_USE_FORMAT_ATTR7_PAL 0
#define DISPHSTX_USE_FORMAT_ATTR8_PAL 0

#endif
